Setup
eHealthAfrica/aether-python-library pull request #1
Opened 2019-08-28 11:24 UTC by lordmallam

2019-08-28 11:58 UTC, obdulia-losantos commented on README.md
> +```
Docs are overrated!

2019-08-28 12:00 UTC, obdulia-losantos commented on README.md
> +REDIS_TASK.publish(task=document, type=document_type, tenant=aether_tenant) # this will trigger the 'handle_callback' function with the published document to all subscribed clients
No closing "```"

2019-08-29 08:34 UTC, shawnsarwar requested changes
Looking good. There are a few binaries that snuck in that I think should be removed (and maybe add .pyc to gitignore) like:
` aether/python/entity/tests/__pycache__/test_extractor.cpython-36-pytest-5.1.1.pyc`

2019-08-29 10:25 UTC, shawnsarwar approved these changes

2019-08-29 11:48 UTC, merged